url: http://localhost:8000
groups:
  - name: default
    prefix: /page/Controleur.php
    model:
      Localisation: int
      Newsletter: int
      UserId: int
      UserMail: email
      Fonction: AddUser
      Genre: string
      Nom: string
      Prenom: string
      Company: string
      Email: email
      Telephone: phone
      Adresse: address
      Code_Postal: postal_code
      Ville: string
      Date_Naissance: date
    routes:
      - name: add
        method: POST
        path:
        headers:
          - name: Content-Type
            value: text/plain
        asserts:
          status:
            code: 200
            type: equal
          schema:
            - type: notNull
            - type: notFound
              schema:
                Result:
                  body:
                    error: string
