url: http://localhost
groups:
  - name: default
    prefix: /api
    model:
      name: string # available value : string, int, email, phone, address, postal_code, date; if value not recognize, keep value
    routes:
      - name: add
        method: POST
        path: "/"
        format: form # available value : json, form
        headers:
          - name: Content-Type
            value: application/json
        asserts:
          status:
            code: 200
            type: equal
          headers:
            - name: location
              type: url # available value : string, int, url, bool
          schema:
            - type: notNull
            - type: notFound
              schema:
                curl_error: string # available value : string, int, url, bool
            - type: found
              schema:
                id: int # available value : string, int, url, bool